name: MicroservicesFeed
dashboardPort: 7001

services:
- name: redis
  image: redis
  bindings:
    - port: 6379
      connectionString: ${host}:${port}
  volumes:
    - source: .redis
      target: /data
      name: redis-volume
  tags:
    - infrastructure

- name: pulsar
  image: apachepulsar/pulsar
  bindings:
    - port: 6650
      protocol: pulsar
  args: "bin/pulsar standalone"
  volumes:
    - source: .pulsar
      target: /pulsar/data
      name: pulsar-volume
  tags:
    - infrastructure

- name: microservices-feed-gateway
  project: src/Gateway/MicroservicesFeed.Gateway/MicroservicesFeed.Gateway.csproj
  bindings:
    - port: 7000
      protocol: https
  env:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development

- name: microservices-feed-aggregator
  project: src/Aggregator/MicroservicesFeed.Aggregator/MicroservicesFeed.Aggregator.csproj
  bindings:
    - port: 7010
      protocol: https
  env:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development

- name: microservices-feed-notifier
  project: src/Notifier/MicroservicesFeed.Notifier/MicroservicesFeed.Notifier.csproj
  bindings:
    - port: 7020
      protocol: https
  env:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development

- name: microservices-feed-news
  project: src/Services/News/MicroservicesFeed.News/MicroservicesFeed.News.csproj
  bindings:
    - port: 7030
      protocol: https
  env:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development

- name: microservices-feed-quotes
  project: src/Services/Quotes/MicroservicesFeed.Quotes/MicroservicesFeed.Quotes.csproj
  bindings:
    - port: 7040
      protocol: https
  env:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development

- name: microservices-feed-weather
  project: src/Services/Weather/MicroservicesFeed.Weather/MicroservicesFeed.Weather.csproj
  bindings:
    - port: 7050
      protocol: https
  env:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development